<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kintino.CipherConf.IO.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Kintino.CipherConf.App\Kintino.CipherConf.App.csproj" />
  </ItemGroup>

</Project>
