<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <PackAsTool>true</PackAsTool>
    <AssemblyName>sigaba</AssemblyName>
    <ToolCommandName>sigaba</ToolCommandName>
    <PackageOutputPath>./nupkg</PackageOutputPath>
    <PackageVersion>0.0.0</PackageVersion>
    <Description>
      Command-line tool for json project settings encryption/decryption.
    </Description>
  </PropertyGroup>

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>CA1873;IDE0290</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sigaba.Cli.IntegrationTest" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.10" />
    <PackageReference Include="Spectre.Console.Cli" Version="0.55.0" />
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sigaba.App\Sigaba.App.csproj" />
  </ItemGroup>

</Project>
