<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kintino.CipherConf.Documents.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Kintino.CipherConf.Documents.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EncryptConfig.Common\Kintino.CipherConf.Common.csproj" />
    <ProjectReference Include="..\Kintino.CipherConf.Crypto\Kintino.CipherConf.Crypto.csproj" />
  </ItemGroup>


</Project>
