<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sigaba.Documents.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Sigaba.Documents.Primitives" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sigaba.Common\Sigaba.Common.csproj" />
    <ProjectReference Include="..\Sigaba.Crypto\Sigaba.Crypto.csproj" />
  </ItemGroup>


</Project>
