<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Sigaba.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Sigaba.App.Loaders.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Sigaba.App.Exceptions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.10" />
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
    <PackageReference Include="Vipentti.IO.Abstractions.FileSystemGlobbing" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Sigaba.Common\Sigaba.Common.csproj" />
    <ProjectReference Include="..\Sigaba.Crypto\Sigaba.Crypto.csproj" />
  </ItemGroup>

</Project>
