<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Kintino.CipherConf.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Kintino.CipherConf.App.Persistence.Test" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Kintino.CipherConf.App.Exceptions" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.10" />
    <PackageReference Include="Microsoft.Extensions.FileSystemGlobbing" Version="10.0.10" />
    <PackageReference Include="System.IO.Abstractions" Version="22.2.0" />
    <PackageReference Include="Vipentti.IO.Abstractions.FileSystemGlobbing" Version="1.0.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EncryptConfig.Common\Kintino.CipherConf.Common.csproj" />
    <ProjectReference Include="..\Kintino.CipherConf.Crypto\Kintino.CipherConf.Crypto.csproj" />
  </ItemGroup>

</Project>
