name: CD
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
env:
  major: 0
  minor: 2
  tag: "" # Set this to "-beta" or "-rc" for pre-release versions
jobs:
  publish:
    name: Build and Publish to NuGet
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set version
        run: echo "APP_VERSION=${{ env.major }}.${{ env.minor }}.${{ github.run_number }}${{ env.tag }}" >> $GITHUB_ENV
      - name: NuGet login
        uses: NuGet/login@v1
        id: login
        with:
          user: ${{ secrets.NUGET_USER }}
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: >-
          dotnet  build 
          --configuration Release 
          --no-restore
          /p:Version=${{ env.APP_VERSION }}
      - name: Test
        run: dotnet test --configuration Release --no-build --verbosity normal
      - name: Pack
        run: >-
          dotnet pack Sigaba.Cli/Sigaba.Cli.csproj 
          --output ./artifacts
          --configuration Release 
          --no-restore 
          --no-build
          /p:PackageVersion=${{ env.APP_VERSION }}
      - name: Push to NuGet
        run: >-
          dotnet nuget push ./artifacts/*.nupkg 
          --source https://api.nuget.org/v3/index.json
          --api-key ${{steps.login.outputs.NUGET_API_KEY}}
          --skip-duplicate